baseURL = "https://hyrahmo-e2m.pages.dev/"
languageCode = "ru"
title = "Hyrahmo"
theme = "PaperMod"
paginate = 10

[params]
  author = "hyrahmo"
  defaultTheme = "auto"
  showReadingTime = true
  showShareButtons = true
  showPostNavLinks = true
  showToc = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  comments = false
  assetsDir = "static/images"

[params.profileMode]
  enabled = true
  title = "Hyrahmo"
  subtitle = "Блог и проекты"
  imageUrl = "images/avatar.png"
  imageWidth = 120
  imageHeight = 120
  buttons = [
    { name = "Блог", url = "/posts/" },
    { name = "Обо мне", url = "/about/" },
    { name = "Контакты", url = "/contact/" }
  ]

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Блог"
    url = "/posts/"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "Обо мне"
    url = "/about/"
    weight = 20

  [[menu.main]]
    identifier = "contact"
    name = "Контакты"
    url = "/contact/"
    weight = 30

